### ISSUE TITLE
我喜欢您的项目，这太神奇了！

### ISSUE THREAD

**Issue by lfj-io** [baiyukey/headLoader#3]
我对你的项目很感兴趣，看起来很强大！，我想问一下，远程文件导入怎么样，像这个也能用吗？:
`<script type="text/javascript" data-dir="https://cdn.jsdelivr.net/npm/" .... `

**Comment by baiyukey** [comment]
非常高兴您对我的项目感兴趣，远程标签也是可以的，但是对于远程文件，处理时只使用script标签引用，不会做缓存处理。
