### ISSUE TITLE
每个css / js文件中包含的路径均无法正常工作。

### ISSUE THREAD

**Issue by adnhung** [baiyukey/headLoader#4]
由于中文不是我的母语，因此我将举一个具体的例子。希望你能理解。

例如。我的网站位于*something.com/myweb/index.htm*
 我的css文件位于 something.com/myweb/css/style.css,文件包含：
`body{background: url(../images/xxx.jpg);}`
如果使用以下方法：`<link rel="stylesheet" href="css/style.css">`，则它应该可以正常工作。
但是对于headLoader，找不到  “images/xxx.jpg”。

**Comment by baiyukey** [comment]
你好，非常感谢您对我的项目感兴趣。
由于"headerLoader.js"会把所有的css读取完成后写到缓存中，再次使用时从缓存中读取，而不是请求服务器获取一个引用数据，所以在应用到html文件中时，并不是引用方式，而是最终将CSS内容写到html文件中，
因此，在css文件中定义的图片路径，应该使用绝对路径，来保证不同目录层次的html文件在访问时都能够正确指向，所以图片路径应该类似这样：
"/myweb/images/xxx.jpg"
再次感谢您"star"我的项目。

**Comment by adnhung** [comment]
> 你好，非常感谢您对我的项目感兴趣。
> 由于"headerLoader.js"会把所有的css读取完成后写到缓存中，再次使用时从缓存中读取，而不是请求服务器获取一个引用数据，所以在应用到html文件中时，并不是引用方式，而是最终将CSS内容写到html文件中，
> 因此，在css文件中定义的图片路径，应该使用绝对路径，来保证不同目录层次的html文件在访问时都能够正确指向，所以图片路径应该类似这样：
> "/myweb/images/xxx.jpg"
> 再次感谢您"star"我的项目。

如果headerLoader能够记住所包含文件的路径并自动在其内部重建所有路径，那就太好了。

**Comment by baiyukey** [comment]
> > 您好，非常感谢您对我的项目感兴趣。
> > 由于“ headerLoader.js”会把所有的css读取完成后写到缓存中，再次使用时从缓存中读取，而不是请求服务器获取一个引用数据，因此在应用到html文件中时，并非引用方式，而是最终将CSS内容写到html文件中，
> > 因此，在css文件中定义的图片路径，应该使用绝对路径，来保证不同目录层次的html文件在访问时都能够正确指向，所以图片路径应该类似的方式：
> > “ /myweb/images/xxx.jpg”再次确认
> > 您“ star”我的项目。
> 
> 如果headerLoader能够记住所包含文件的路径并自动在其内部重建所有路径，那就太好了。

感谢您的建议，不过出于性能的考虑，我并不打算那么做，如果从缓存中读取后要重新计算文件路径并替换路径字符串的化会影响效率，这有背于headLoader.js的初衷。

> > 你好，非常感谢您对我的项目感兴趣。
> > 由于"headerLoader.js"会把所有的css读取完成后写到缓存中，再次使用时从缓存中读取，而不是请求服务器获取一个引用数据，所以在应用到html文件中时，并不是引用方式，而是最终将CSS内容写到html文件中，
> > 因此，在css文件中定义的图片路径，应该使用绝对路径，来保证不同目录层次的html文件在访问时都能够正确指向，所以图片路径应该类似这样：
> > "/myweb/images/xxx.jpg"
> > 再次感谢您"star"我的项目。
> 
> 如果headerLoader能够记住所包含文件的路径并自动在其内部重建所有路径，那就太好了。

感谢您的建议，然而那么做会得不偿失，因为从缓存中读取数据后，如果要重新计算文件路径并替换路径字符串，这样势必影响效率，尤其是在这个文件被更多的页面文件使用时，影响会成倍增长，这有背于headLoader.js的初衷。

**Comment by baiyukey** [comment]
> > 你好，非常感谢您对我的项目感兴趣。
> > 由于"headerLoader.js"会把所有的css读取完成后写到缓存中，再次使用时从缓存中读取，而不是请求服务器获取一个引用数据，所以在应用到html文件中时，并不是引用方式，而是最终将CSS内容写到html文件中，
> > 因此，在css文件中定义的图片路径，应该使用绝对路径，来保证不同目录层次的html文件在访问时都能够正确指向，所以图片路径应该类似这样：
> > "/myweb/images/xxx.jpg"
> > 再次感谢您"star"我的项目。
> 
> 如果headerLoader能够记住所包含文件的路径并自动在其内部重建所有路径，那就太好了。

感谢您的建议，然而那么做会得不偿失，因为从缓存中读取数据后，如果要重新计算文件路径并替换路径字符串，这样势必影响效率，尤其是在这个文件被更多的页面文件使用时，影响会成倍增长，这有背于headLoader.js的初衷。

**Comment by lfj-io** [comment]
> 感谢您的建议，然而那么做会得不偿失，因为从缓存中读取数据后，如果要重新计算文件路径并替换路径字符串，这样势必影响效率，尤其是在这个文件被更多的页面文件使用时，影响会成倍增长，这有背于headLoader.js的初衷。

为什么不只做一次呢？ 像这个步骤：
-headerLoader获取资源。 ==> 重建路径 ==>保存到缓存.

**Comment by adnhung** [comment]
> 为什么不只做一次呢？ 像这个步骤：
> -headerLoader获取资源。 ==> 重建路径 ==>保存到缓存.

我同意，我认为这是可能的，因为只完成一次，结果就会被缓存，因此重新加载时不会降低性能。

**Comment by lfj-io** [comment]
> 您还可以读取文件的元数据来验证修改日期，那将是非常不错的。
> 例如下面只加载“ head”，文件内容将不会下载，因此性能也可以得到提高。

使用此选项时，只需注意服务器端的快取原則。

无论如何，我要感谢baiyukey这个很棒的模块。 当我自定义它以隐藏我的脚本源时，无法通过devtools的网络控制台进行检测。 这很有用，我的脚本源已完全隐藏，无法再被network tool检测到。

![image](https://user-images.githubusercontent.com/73473330/106768746-cdcafc80-666e-11eb-9606-3d402327973d.png)

**Comment by baiyukey** [comment]
> > 为什么不只做一次呢？ 像这个步骤：
> > -headerLoader获取资源。 ==> 重建路径 ==>保存到缓存.
> 
> 我同意，我认为这是可能的，因为只完成一次，结果就会被缓存，因此重新加载时不会降低性能。
> 
> 您还可以计算文件的md5（或长度），然后将其保存到headerLoader，如果在生命周期结束后文件相同，则不要重建任何内容，只是增加时间。
> 
> 你可以参考这个md5模块 [emn178/js-md5](https://github.com/emn178/js-md5)
> 
> 不建议检测文件长度。 因为当我替换字符时。 例如：从 `if(a<b)` 变为 `if(a>b)`，那么文件将具有相同的长度。
> 
> 您还可以读取文件的元数据来验证修改日期，那将是非常不错的。
> 重新计算文件会降低性能，因此，当记住并检测文件更改时，以防止在文件相同时进行重建步骤，从而可以提高性能。
> 例如下面只加载“ head”，文件内容将不会下载，因此性能也可以得到提高。
> 
> ```
> function fetchHeader(url, wch) {
>     try {
>         var req=new XMLHttpRequest();
>         req.open("HEAD", url, false);
>         req.send(null);
>         if(req.status== 200){
>             return req.getResponseHeader(wch);
>         }
>         else return false;
>     } catch(er) {
>         return er.message;
>     }
> }
> alert(fetchHeader('URL FILE','Last-Modified'));
> ```

先检测文件是否改动的方法不错，感谢您的建议。

**Comment by baiyukey** [comment]
> > 感谢您的建议，然而那么做会得不偿失，因为从缓存中读取数据后，如果要重新计算文件路径并替换路径字符串，这样势必影响效率，尤其是在这个文件被更多的页面文件使用时，影响会成倍增长，这有背于headLoader.js的初衷。
> 
> 为什么不只做一次呢？ 像这个步骤：
> -headerLoader获取资源。 ==> 重建路径 ==>保存到缓存.

如果这样，不同层级的页面文件使用同一个缓存时可能会出现问题。

**Comment by TheWolds** [comment]
> 如果这样，不同层级的页面文件使用同一个缓存时可能会出现问题。

似乎比我想的还要复杂！ 为此，您可以尝试捕获xhr.responseURL事件以为headerLoader通过XHR检索到的每个文件重建链接（正则表达式）。

**Comment by adnhung** [comment]
> 如果这样，不同层级的页面文件使用同一个缓存时可能会出现问题。

似乎比我想的还要复杂！ 为此，您可以尝试捕获xhr.responseURL事件以为headerLoader通过XHR检索到的每个文件重建链接（正则表达式）。
